version: "3.1"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/.
      dockerfile: Dockerfile.development
    volumes:
      - ./frontend/src/:/app/src:delegated
      - ./frontend/public/:/app/public
      - ./frontend/index.html:/app/index.html
    expose:
      - 3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=80
    networks:
      - task_network
    restart: always

  gateway:
    container_name: gateway
    build:
      context: ./gateway/development/.
      dockerfile: Dockerfile
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - task_network
    depends_on:
      frontend:
        condition: service_started
    restart: always

networks:
  task_network:
    driver: "bridge"
