version: "3.1"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/.
      dockerfile: Dockerfile.production
    expose:
      - 3000
    networks:
      - task_network
    restart: always

  gateway:
    container_name: gateway
    build:
      context: ./gateway/production/.
      dockerfile: Dockerfile
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - task_network
    depends_on:
      frontend:
        condition: service_started
    restart: always

networks:
  task_network:
    driver: "bridge"
